import React, { useState } from 'react';
import ScenarioCard from './ScenarioCard';
import LoadingSpinner from '../ui/LoadingSpinner';
import styles from '../../styles/ChallengeArena.module.css';
import { mockChallenges } from '../../data/mockChallenges';
import useChallenge from '../../hooks/useChallenge';
import type { Agent, ChallengeScenario } from '../../types';

interface ChallengeArenaProps {
  agent: Agent;
  }

  const ChallengeArena: React.FC<ChallengeArenaProps> = ({ agent }) => {
    const [selected, setSelected] = useState<ChallengeScenario | null>(null);
      const { result, isRunning, error, startChallenge, resetChallenge } =
          useChallenge();

            const handleRun = async () => {
                if (!selected) return;
                    await startChallenge(agent, selected);
                      };

                        const handleReset = () => {
                            setSelected(null);
                                resetChallenge();
                                  };

                                    return (
                                        <div className={styles.wrapper}>
                                              <div className={styles.header}>
                                                      <h2 className={styles.heading}>Challenge Arena</h2>
                                                              <p className={styles.subtext}>
                                                                        Test <strong>{agent.name}</strong> against a real DeFi scenario
                                                                                  before committing capital.
                                                                                          </p>
                                                                                                </div>

                                                                                                      {!result && (
                                                                                                              <>
                                                                                                                        <div className={styles.scenarios}>
                                                                                                                                    {mockChallenges.map(scenario => (
                                                                                                                                                  <ScenarioCard
                                                                                                                                                                  key={scenario.id}
                                                                                                                                                                                  scenario={scenario}
                                                                                                                                                                                                  isSelected={selected?.id === scenario.id}
                                                                                                                                                                                                                  onSelect={setSelected}
                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                {isRunning ? (
                                                                                                                                                                                                                                                                            <LoadingSpinner message="Running challenge simulation..." />
                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                className={styles.run}
                                                                                                                                                                                                                                                                                                                              onClick={handleRun}
                                                                                                                                                                                                                                                                                                                                            disabled={!selected}
                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                      {selected ? `Run: ${selected.title}` : 'Select a Scenario'}
                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                      {error && <p className={styles.error}>{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                          {result && (
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className={styles.result}>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                        className={[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      styles.verdict,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result.passed ? styles.passed : styles.failed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ].join(' ')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {result.passed ? '✓ Challenge Passed' : '✗ Challenge Failed'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className={styles.score}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className={styles.scoreValue}>{result.score}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className={styles.scoreLabel}>Simulation Score</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className={styles.analysis}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h4>Analysis</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>{result.analysis}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {result.recommendations.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className={styles.recommendations}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h4>Recommendations</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {result.recommendations.map((rec, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li key={i}>{rec}</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button className={styles.reset} onClick={handleReset}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Run Another Challenge
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default ChallengeArena;