import React from 'react';
import styles from '../../styles/FilterBar.module.css';
import type { FilterState, AgentSpecialty, AgentStatus } from '../../types';
import { AGENT_SPECIALTY_OPTIONS, SORT_OPTIONS } from '../../config/constants';

interface FilterBarProps {
  filters: FilterState;
    onSpecialtyChange: (value: AgentSpecialty | 'All') => void;
      onStatusChange: (value: AgentStatus | 'All') => void;
        onMinScoreChange: (value: number) => void;
          onSortChange: (value: FilterState['sortBy']) => void;
            onReset: () => void;
            }

            const FilterBar: React.FC<FilterBarProps> = ({
              filters,
                onSpecialtyChange,
                  onStatusChange,
                    onMinScoreChange,
                      onSortChange,
                        onReset
                        }) => {
                          return (
                              <div className={styles.bar}>
                                    <div className={styles.filters}>
                                            <select
                                                      value={filters.specialty}
                                                                onChange={e => onSpecialtyChange(e.target.value as AgentSpecialty | 'All')}
                                                                          className={styles.select}
                                                                                  >
                                                                                            <option value="All">All Specialties</option>
                                                                                                      {AGENT_SPECIALTY_OPTIONS.map(opt => (
                                                                                                                  <option key={opt} value={opt}>{opt}</option>
                                                                                                                            ))}
                                                                                                                                    </select>

                                                                                                                                            <select
                                                                                                                                                      value={filters.status}
                                                                                                                                                                onChange={e => onStatusChange(e.target.value as AgentStatus | 'All')}
                                                                                                                                                                          className={styles.select}
                                                                                                                                                                                  >
                                                                                                                                                                                            <option value="All">All Statuses</option>
                                                                                                                                                                                                      <option value="active">Active</option>
                                                                                                                                                                                                                <option value="inactive">Inactive</option>
                                                                                                                                                                                                                          <option value="challenged">Challenged</option>
                                                                                                                                                                                                                                  </select>

                                                                                                                                                                                                                                          <select
                                                                                                                                                                                                                                                    value={filters.sortBy}
                                                                                                                                                                                                                                                              onChange={e => onSortChange(e.target.value as FilterState['sortBy'])}
                                                                                                                                                                                                                                                                        className={styles.select}
                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                          {SORT_OPTIONS.map(opt => (
                                                                                                                                                                                                                                                                                                      <option key={opt.value} value={opt.value}>{opt.label}</option>
                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                        </select>

                                                                                                                                                                                                                                                                                                                                <div className={styles.scoreFilter}>
                                                                                                                                                                                                                                                                                                                                          <label className={styles.scoreLabel}>
                                                                                                                                                                                                                                                                                                                                                      Min Score: <span>{filters.minScore}</span>
                                                                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                      type="range"
                                                                                                                                                                                                                                                                                                                                                                                                  min={0}
                                                                                                                                                                                                                                                                                                                                                                                                              max={100}
                                                                                                                                                                                                                                                                                                                                                                                                                          value={filters.minScore}
                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={e => onMinScoreChange(Number(e.target.value))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={styles.range}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className={styles.reset} onClick={onReset}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Reset
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default React.memo(FilterBar);