import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import CredenceScore from './CredenceScore';
import TrackRecord from './TrackRecord';
import Badge from '../ui/Badge';
import ConfirmModal from '../ui/ConfirmModal';
import styles from '../../styles/AgentProfile.module.css';
import type { Agent } from '../../types';

interface AgentProfileProps {
  agent: Agent;
    onChallenge: () => void;
    }

    const getStatusVariant = (status: Agent['status']) => {
      if (status === 'active') return 'green';
        if (status === 'challenged') return 'warning';
          return 'neutral';
          };

          const AgentProfile: React.FC<AgentProfileProps> = ({ agent, onChallenge }) => {
            const navigate = useNavigate();
              const [showHireModal, setShowHireModal] = useState(false);

                const handleHireConfirm = () => {
                    setShowHireModal(false);
                        navigate('/marketplace');
                          };

                            return (
                                <div className={styles.wrapper}>
                                      <button className={styles.back} onClick={() => navigate('/marketplace')}>
                                              ← Back to Marketplace
                                                    </button>

                                                          <div className={styles.header}>
                                                                  <div className={styles.identity}>
                                                                            <h1 className={styles.name}>{agent.name}</h1>
                                                                                      <div className={styles.badges}>
                                                                                                  <Badge label={agent.specialty} variant="neutral" />
                                                                                                              <Badge
                                                                                                                            label={agent.status.toUpperCase()}
                                                                                                                                          variant={getStatusVariant(agent.status)}
                                                                                                                                                      />
                                                                                                                                                                </div>
                                                                                                                                                                          <p className={styles.erc}>
                                                                                                                                                                                      ERC-8004 ID: <span>{agent.erc8004Id}</span>
                                                                                                                                                                                                </p>
                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                <CredenceScore score={agent.credenceScore} />
                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                            <p className={styles.description}>{agent.description}</p>

                                                                                                                                                                                                                                  <div className={styles.stats}>
                                                                                                                                                                                                                                          <div className={styles.stat}>
                                                                                                                                                                                                                                                    <span className={styles.statValue}>{agent.successRate}%</span>
                                                                                                                                                                                                                                                              <span className={styles.statLabel}>Success Rate</span>
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                              <div className={styles.stat}>
                                                                                                                                                                                                                                                                                        <span className={styles.statValue}>{agent.avgReturn}%</span>
                                                                                                                                                                                                                                                                                                  <span className={styles.statLabel}>Avg Return</span>
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                  <div className={styles.stat}>
                                                                                                                                                                                                                                                                                                                            <span className={styles.statValue}>
                                                                                                                                                                                                                                                                                                                                        {agent.stakedMNT.toLocaleString()} MNT
                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                            <span className={styles.statLabel}>Staked</span>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                            <div className={styles.stat}>
                                                                                                                                                                                                                                                                                                                                                                                      <span className={styles.statValue}>{agent.totalTasks}</span>
                                                                                                                                                                                                                                                                                                                                                                                                <span className={styles.statLabel}>Total Tasks</span>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.actions}>
                                                                                                                                                                                                                                                                                                                                                                                                                            <button className={styles.challenge} onClick={onChallenge}>
                                                                                                                                                                                                                                                                                                                                                                                                                                      Run Challenge
                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={styles.hire}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setShowHireModal(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Hire Agent
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TrackRecord records={agent.performanceHistory} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {showHireModal && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ConfirmModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="Hire Agent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message={`You are about to hire ${agent.name}. This agent has staked ${agent.stakedMNT.toLocaleString()} MNT as collateral. Their Credence Score is ${agent.credenceScore}. Are you sure?`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            confirmLabel="Hire Now"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onConfirm={handleHireConfirm}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onCancel={() => setShowHireModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default AgentProfile;