import React, { useState } from 'react';
import styles from '../../styles/StakeToList.module.css';
import type { StakeFormData, AgentSpecialty } from '../../types';
import { AGENT_SPECIALTY_OPTIONS, STAKE_MINIMUM_MNT, STAKE_MAXIMUM_MNT } from '../../config/constants';
import Toast from '../ui/Toast';

const initialForm: StakeFormData = {
  agentName: '',
    specialty: 'Yield Optimization',
      description: '',
        stakeAmount: STAKE_MINIMUM_MNT
        };

        const StakeToList: React.FC = () => {
          const [form, setForm] = useState<StakeFormData>(initialForm);
            const [isSubmitting, setIsSubmitting] = useState(false);
              const [toast, setToast] = useState<string | null>(null);
                const [errors, setErrors] = useState<Partial<StakeFormData>>({});

                  const validate = (): boolean => {
                      const newErrors: Partial<StakeFormData> = {};
                          if (!form.agentName.trim()) newErrors.agentName = 'Agent name is required';
                              if (!form.description.trim()) newErrors.description = 'Description is required';
                                  if (form.description.trim().length < 20)
                                        newErrors.description = 'Description must be at least 20 characters';
                                            if (form.stakeAmount < STAKE_MINIMUM_MNT)
                                                  newErrors.stakeAmount = STAKE_MINIMUM_MNT;
                                                      setErrors(newErrors);
                                                          return Object.keys(newErrors).length === 0;
                                                            };

                                                              const handleSubmit = async () => {
                                                                  if (!validate()) return;
                                                                      try {
                                                                            setIsSubmitting(true);
                                                                                  await new Promise(resolve => setTimeout(resolve, 1500));
                                                                                        setToast('Agent submitted successfully! Pending ERC-8004 verification.');
                                                                                              setForm(initialForm);
                                                                                                    setErrors({});
                                                                                                        } catch {
                                                                                                              setToast('Submission failed. Please try again.');
                                                                                                                  } finally {
                                                                                                                        setIsSubmitting(false);
                                                                                                                            }
                                                                                                                              };

                                                                                                                                return (
                                                                                                                                    <div className={styles.wrapper}>
                                                                                                                                          <div className={styles.header}>
                                                                                                                                                  <h2 className={styles.heading}>List Your Agent</h2>
                                                                                                                                                          <p className={styles.subtext}>
                                                                                                                                                                    Stake $MNT to list your AI agent on Credence. Your stake is held as
                                                                                                                                                                              collateral — underperformance or malicious activity results in slashing.
                                                                                                                                                                                      </p>
                                                                                                                                                                                            </div>

                                                                                                                                                                                                  <div className={styles.form}>
                                                                                                                                                                                                          <div className={styles.field}>
                                                                                                                                                                                                                    <label className={styles.label}>Agent Name</label>
                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                          type="text"
                                                                                                                                                                                                                                                      value={form.agentName}
                                                                                                                                                                                                                                                                  onChange={e => setForm(prev => ({ ...prev, agentName: e.target.value }))}
                                                                                                                                                                                                                                                                              placeholder="e.g. YieldMaxx"
                                                                                                                                                                                                                                                                                          maxLength={40}
                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                              {errors.agentName && (
                                                                                                                                                                                                                                                                                                                          <span className={styles.error}>{errors.agentName}</span>
                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                    <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                              <label className={styles.label}>Specialty</label>
                                                                                                                                                                                                                                                                                                                                                                        <select
                                                                                                                                                                                                                                                                                                                                                                                    value={form.specialty}
                                                                                                                                                                                                                                                                                                                                                                                                onChange={e =>
                                                                                                                                                                                                                                                                                                                                                                                                              setForm(prev => ({
                                                                                                                                                                                                                                                                                                                                                                                                                              ...prev,
                                                                                                                                                                                                                                                                                                                                                                                                                                              specialty: e.target.value as AgentSpecialty
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {AGENT_SPECIALTY_OPTIONS.map(opt => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option key={opt} value={opt}>{opt}</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className={styles.label}>Description</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={form.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={e =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setForm(prev => ({ ...prev, description: e.target.value }))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Describe what your agent does, which Mantle protocols it uses, and how it manages risk..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rows={4}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {errors.description && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className={styles.error}>{errors.description}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className={styles.label}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Stake Amount (MNT)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className={styles.range}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Min: {STAKE_MINIMUM_MNT.toLocaleString()} — Max:{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {STAKE_MAXIMUM_MNT.toLocaleString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={form.stakeAmount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            min={STAKE_MINIMUM_MNT}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        max={STAKE_MAXIMUM_MNT}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={e =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setForm(prev => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ...prev,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  stakeAmount: Number(e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {errors.stakeAmount && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className={styles.error}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Minimum stake is {STAKE_MINIMUM_MNT.toLocaleString()} MNT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className={styles.notice}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>⬡</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Your agent will be verified via ERC-8004 on Mantle before going live.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            SP1 ZK proofs will validate all future performance records.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={styles.submit}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={handleSubmit}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    disabled={isSubmitting}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {isSubmitting ? 'Submitting...' : 'Stake & List Agent'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {toast && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Toast
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message={toast}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="success"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClose={() => setToast(null)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default StakeToList;